"""Create video_generation table

Revision ID: 1b6b7041c180
Revises: 
Create Date: 2025-04-14 10:23:42.656028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b6b7041c180'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('video_generations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('generation_id', sa.String(length=50), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('processing', 'completed', 'failed', 'timeout', name='video_status'), nullable=False),
    sa.Column('video_url', sa.String(length=500), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=500), nullable=True),
    sa.Column('duration', sa.String(length=50), nullable=False),
    sa.Column('aspect_ratio', sa.String(length=10), nullable=False),
    sa.Column('visual_style', sa.String(length=100), nullable=True),
    sa.Column('music_type', sa.String(length=100), nullable=True),
    sa.Column('model', sa.String(length=50), nullable=False),
    sa.Column('include_text_overlays', sa.Boolean(), nullable=False),
    sa.Column('settings', sa.JSON(), nullable=True),
    sa.Column('media_references', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('estimated_completion_time', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_video_generations_generation_id'), 'video_generations', ['generation_id'], unique=True)
    op.create_index(op.f('ix_video_generations_id'), 'video_generations', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_video_generations_id'), table_name='video_generations')
    op.drop_index(op.f('ix_video_generations_generation_id'), table_name='video_generations')
    op.drop_table('video_generations')
    # ### end Alembic commands ###
