"""Update video schema

Revision ID: 2a9c6b3e7245
Revises: 1b6b7041c180
Create Date: 2025-04-20 15:30:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2a9c6b3e7245'
down_revision: Union[str, None] = '1b6b7041c180'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Add provider column to video_generations table
    op.add_column('video_generations', sa.Column('provider', sa.String(length=50), nullable=False, server_default='luma'))
    
    # Add preview_url column
    op.add_column('video_generations', sa.Column('preview_url', sa.String(length=500), nullable=True))
    
    # Add metadata_json column (renamed from 'metadata' to avoid reserved name)
    op.add_column('video_generations', sa.Column('metadata_json', sa.JSON(), nullable=True))
    
    # Drop unneeded columns that are now in metadata
    op.drop_column('video_generations', 'visual_style')
    op.drop_column('video_generations', 'music_type')
    op.drop_column('video_generations', 'include_text_overlays')
    op.drop_column('video_generations', 'settings')
    op.drop_column('video_generations', 'media_references')
    op.drop_column('video_generations', 'error_message')
    op.drop_column('video_generations', 'estimated_completion_time')
    
    # Update status enum
    # First create new enum with the correct values
    video_status_new = sa.Enum('processing', 'completed', 'failed', 'cancelled', name='video_status_new')
    video_status_new.create(op.get_bind())
    
    # Create a new temp status column with the new enum
    op.add_column('video_generations', sa.Column('status_new', video_status_new, nullable=True))
    
    # Update data - this is a basic transformation:
    # - 'processing' -> 'processing'
    # - 'completed' -> 'completed'
    # - 'failed' -> 'failed'
    # - 'timeout' -> 'failed'
    op.execute("UPDATE video_generations SET status_new = 'processing' WHERE status = 'processing'")
    op.execute("UPDATE video_generations SET status_new = 'completed' WHERE status = 'completed'")
    op.execute("UPDATE video_generations SET status_new = 'failed' WHERE status = 'failed'")
    op.execute("UPDATE video_generations SET status_new = 'failed' WHERE status = 'timeout'")
    
    # Drop the old column and rename the new one
    op.drop_column('video_generations', 'status')
    op.alter_column('video_generations', 'status_new', new_column_name='status')
    op.alter_column('video_generations', 'status', nullable=False)
    
    # Drop the old enum
    op.execute('DROP TYPE video_status')
    op.execute('ALTER TYPE video_status_new RENAME TO video_status')
    
    # Create heygen_avatar_videos table
    op.create_table('heygen_avatar_videos',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('video_generation_id', sa.Integer(), nullable=False),
        sa.Column('avatar_id', sa.String(length=100), nullable=False),
        sa.Column('avatar_name', sa.String(length=100), nullable=True),
        sa.Column('avatar_style', sa.String(length=50), nullable=False),
        sa.Column('voice_id', sa.String(length=100), nullable=False),
        sa.Column('voice_speed', sa.Float(), nullable=False),
        sa.Column('voice_pitch', sa.Integer(), nullable=False),
        sa.Column('width', sa.Integer(), nullable=False),
        sa.Column('height', sa.Integer(), nullable=False),
        sa.Column('background_color', sa.String(length=20), nullable=False),
        sa.Column('processing_time', sa.Float(), nullable=True),
        sa.Column('gender', sa.String(length=20), nullable=True),
        sa.Column('language', sa.String(length=50), nullable=True),
        sa.Column('callback_url', sa.String(length=500), nullable=True),
        sa.Column('error_details', sa.JSON(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['video_generation_id'], ['video_generations.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    
    # Create index on avatar_id
    op.create_index(op.f('ix_heygen_avatar_videos_avatar_id'), 'heygen_avatar_videos', ['avatar_id'], unique=False)
    
    # Update generation_id length
    op.alter_column('video_generations', 'generation_id', type_=sa.String(length=100))
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop the heygen_avatar_videos table
    op.drop_index(op.f('ix_heygen_avatar_videos_avatar_id'), table_name='heygen_avatar_videos')
    op.drop_table('heygen_avatar_videos')
    
    # Restore generation_id length
    op.alter_column('video_generations', 'generation_id', type_=sa.String(length=50))
    
    # Create a new enum with the old values
    video_status_old = sa.Enum('processing', 'completed', 'failed', 'timeout', name='video_status_old')
    video_status_old.create(op.get_bind())
    
    # Create a temporary status column
    op.add_column('video_generations', sa.Column('status_old', video_status_old, nullable=True))
    
    # Convert data back
    op.execute("UPDATE video_generations SET status_old = 'processing' WHERE status = 'processing'")
    op.execute("UPDATE video_generations SET status_old = 'completed' WHERE status = 'completed'")
    op.execute("UPDATE video_generations SET status_old = 'failed' WHERE status = 'failed'")
    op.execute("UPDATE video_generations SET status_old = 'timeout' WHERE status = 'cancelled'")
    
    # Drop old column and rename new one
    op.drop_column('video_generations', 'status')
    op.alter_column('video_generations', 'status_old', new_column_name='status')
    op.alter_column('video_generations', 'status', nullable=False)
    
    # Drop the new enum and rename the old one
    op.execute('DROP TYPE video_status')
    op.execute('ALTER TYPE video_status_old RENAME TO video_status')
    
    # Add back removed columns
    op.add_column('video_generations', sa.Column('visual_style', sa.String(length=100), nullable=True))
    op.add_column('video_generations', sa.Column('music_type', sa.String(length=100), nullable=True))
    op.add_column('video_generations', sa.Column('include_text_overlays', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('video_generations', sa.Column('settings', sa.JSON(), nullable=True))
    op.add_column('video_generations', sa.Column('media_references', sa.JSON(), nullable=True))
    op.add_column('video_generations', sa.Column('error_message', sa.Text(), nullable=True))
    op.add_column('video_generations', sa.Column('estimated_completion_time', sa.String(length=100), nullable=True))
    
    # Drop new columns
    op.drop_column('video_generations', 'metadata_json')
    op.drop_column('video_generations', 'preview_url')
    op.drop_column('video_generations', 'provider')
    
    # ### end Alembic commands ### 