"""update workspace architecture

Revision ID: 3b94de23ac85
Revises: ab0a61f41d96
Create Date: 2025-05-15 12:43:58.865020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b94de23ac85'
down_revision: Union[str, None] = 'ab0a61f41d96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_workspaces', sa.Column('role', sa.String(length=50), nullable=False))
    op.add_column('user_workspaces', sa.Column('active', sa.Boolean(), nullable=False))
    op.add_column('workspaces', sa.Column('owner_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'workspaces', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workspaces', type_='foreignkey')
    op.drop_column('workspaces', 'owner_id')
    op.drop_column('user_workspaces', 'active')
    op.drop_column('user_workspaces', 'role')
    # ### end Alembic commands ###
