"""add user/workspace creation date

Revision ID: 5749d60da90f
Revises: 3b94de23ac85
Create Date: 2025-05-15 15:41:03.805830

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5749d60da90f'
down_revision: Union[str, None] = '3b94de23ac85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_workspaces', sa.Column('joined_at', sa.DateTime(), nullable=False))
    op.add_column('users', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('workspaces', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('workspaces', sa.Column('updated_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workspaces', 'updated_at')
    op.drop_column('workspaces', 'created_at')
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    op.drop_column('user_workspaces', 'joined_at')
    # ### end Alembic commands ###
