"""add_project_id_to_asset_tables

Revision ID: ab692caf15ba
Revises: d70ccc3a46be
Create Date: 2025-05-27 08:26:05.216445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab692caf15ba'
down_revision: Union[str, None] = 'd70ccc3a46be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audio', sa.Column('project_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'audio', 'projects', ['project_id'], ['id'])
    op.add_column('images', sa.Column('project_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'images', 'projects', ['project_id'], ['id'])
    op.add_column('lipsync_videos', sa.Column('project_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'lipsync_videos', 'projects', ['project_id'], ['id'])
    op.add_column('videos', sa.Column('project_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'videos', 'projects', ['project_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'videos', type_='foreignkey')
    op.drop_column('videos', 'project_id')
    op.drop_constraint(None, 'lipsync_videos', type_='foreignkey')
    op.drop_column('lipsync_videos', 'project_id')
    op.drop_constraint(None, 'images', type_='foreignkey')
    op.drop_column('images', 'project_id')
    op.drop_constraint(None, 'audio', type_='foreignkey')
    op.drop_column('audio', 'project_id')
    # ### end Alembic commands ###
